version: '3.8'

services:
  app:
    image: mercari-build-training/app:latest
    ports:
      - "9000:9000"
    environment:
      - FRONT_URL=http://localhost:3000
    networks:
      - mercari-network

  web:
    image: mercari-build-training/web:latest
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://app:9000
    depends_on:
      - app
    networks:
      - mercari-network

volumes:
  web-node-modules:

networks:
  mercari-network:
    driver: bridge
